version: "3.7"

services:
  app:
    image: node:12-alpine
    command: npx ts-node index
    environment:
      - PORT
    ports:
      - 3000:${PORT}
    working_dir: /user-demo/src
    volumes:
      - ./:/user-demo
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database-data:
