version: "3.7"

services:
  app:
    image: node:13-alpine
    command: sh -c "npm install && npx tsc && node dist/index.js"
    ports:
      - 3000:3000
    working_dir: /user-demo
    volumes:
      - ./:/user-demo
    links:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database-data:
